---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:ManagedBy: Terraform
  tag:Project: "{{ lookup('env', 'PROJECT_NAME') | default('aws-terraform-infra') }}"
  instance-state-name: running
 keyed_groups:
  - key: tags.Role
    prefix: role_
  - key: tags.Environment
    prefix: env_
  - key: tags.Project
    prefix: project_
hostnames:
  - public-ip-address
  - private-ip-address
compose:
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'~/.ssh/id_rsa'"
  ansible_python_interpreter: "'/usr/bin/python3'"
